name: Release Helm Chart and Build Pages

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: ./my-helm-chart
          pages_branch: gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  page-build-deployment:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout source branch where package.json and package-lock.json live
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: main  # Change this if your source branch is different

      # Install dependencies and build static site
      - name: Install dependencies and build site
        run: |
          npm ci
          npm run build

      # Checkout gh-pages branch to update the site
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # Clear old files and copy new build output (adjust the build output folder if needed)
      - name: Update gh-pages content
        run: |
          rm -rf ./*
          cp -r ./path/to/build/output/* ./

      # Commit and push the changes to gh-pages branch
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update static site"
          git push origin gh-pages