name: Release Helm Chart and Build Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: ./my-helm-chart
          pages_branch: gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  page-build-deployment:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Static Site
        run: |
          # Replace these with your actual static site build commands
          npm ci
          npm run build

      - name: Deploy Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy updated pages [skip ci]" || echo "No changes to commit"
          git push origin gh-pages