name: Release Helm Chart

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write  # sometimes needed for chart releaser auth

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: my-helm-chart
          pages_branch: gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}